[package]
name = "rust_mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]



[dependencies]
bigdecimal = "0.4.3"
rug = "1.24.1"
wasm-bindgen = "0.2.92"

